apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}
