apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: laravel-app
data:
  nginx.conf: |
    server {
        listen 80;
        server_name example.local;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location /resume {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            fastcgi_pass laravel-app-laravel:9000;
            fastcgi_param SCRIPT_FILENAME $document_root/index.php;
            include fastcgi_params;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass laravel-app-laravel:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }
    }

